language: android
jdk: oraclejdk8
env:
  matrix:
  - ANDROID_TARGET=android-23
branches:
  only:
  - master
android:
  components:
  - android-22
  - build-tools-23.0.1
  - extra-google-m2repository
  - extra-android-m2repository
script: ./gradlew --info clean assemble
